name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:17

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: stuff
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 1s
          --health-timeout 30s
          --health-retries 15

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Init Gradle
      run: ./gradlew

    - name: Lint
      run: ./gradlew ktfmtCheck

    - name: Test
      run: ./gradlew test --info
      env:
        DATASOURCE_URL: jdbc:mysql://mysql:3306/stuff
        DATASOURCE_USERNAME: root
        DATASOURCE_PASSWORD:

    - name: Build
      run: ./gradlew bootDistZip
